### ISSUE TITLE
Need ability to add additional url params

### ISSUE THREAD

**Issue by JarrodMFlesch** [trouble/react-modal#2]
The current implementation allows for the modal slug to be updated, but the ability to send additional query params would be ideal.

**Comment by jacobsfletch** [comment]
Could you provide a specific example of what you'd like to see here?

**Comment by JarrodMFlesch** [comment]
@jacobsfletch this actually came from @jmikrut, I just logged it for him. He will know more of what is desired here.

**Comment by jmikrut** [comment]
Ah - yeah.  So, if you want to open a modal and, at the same time, add other URL search parameters, it's impossible using the current implementation. 

But, this is router-dependent and means we need to determine what our future router implementation methodology looks like before we can address this issue.

**Comment by jacobsfletch** [comment]
If you are using an external router (sending a callback function to `handleParamChange`), you can add any additional search parameters while you handle the change.

So do you mean in cases where the parameter is being handled internally? This would be if you set `handleParamChange` as `true`, and then fire either the `toggle` or `open` method, or click on a `ModalToggler` (which fires `toggle`). Are you suggesting adding support for these methods to set additional search parameters ?

**Comment by jacobsfletch** [comment]
Closing. Will re-open if relevant again.
